name: CI Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.16'
          cache: true

      - name: Install libsqlite3-dev
        run: sudo apt-get install libsqlite3-dev

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.16'
          cache: true

      - name: Install linux dependencies
        run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libsqlite3-dev

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build for Linux
        run: flutter build linux --release